### ISSUE TITLE
Automatically call withSocketsDo everywhere

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/http-client#107]
Currently, users must call `withSocketsDo` before using the http library. Likely that was because people assumed it to be expensive, or didn't know how it composed. We now know it isn't expensive, and the rules on how it composes are incredibly flexible: http://neilmitchell.blogspot.co.uk/2015/02/making-withsocketsdo-unnecessary.html

I suggest a call to `withSocketsDo` around each high level operation such as `withManager` (not sure if you're going to need it around `parseUrl`, but you should probably check). If you worry about the performance, I suggest you follow the CAF/unsafePerformIO/evaluate trick from the blog post above, but I doubt its going to be any noticeable performance on any version.

**Comment by snoyberg** [comment]
Sounds good to me. I'll try to look at this some time next week.

**Comment by DanBurton** [comment]
I realize that the motivation to continue providing `withSocketsDo` is for backwards compatibility, but at this point, shouldn't it be deprecated in favor of something like

```haskell
{-# INLINE initSockets #-}
initSockets :: IO ()
#if !defined(WITH_WINSOCK)
initSockets = return ()
#else
initSockets = evaluate withSocketsInit
```

Since we're no longer calling `shutdownWinSock`, there doesn't seem to be any point in retaining the "bracket" call pattern of `withSocketsDo`. If I'm not mistaken, all network activity in `http-client` requires a manager (either explicitly or under the hood), so it should be sufficient to `initSockets` sometime during `newManager`.

That said, I think it would be better to go with Simon Marlow's suggestion to have the initialization happen automatically and leave this stuff out of http-client entirely.

wrt people using old libraries but wanting to program in the new style of not worrying about `withSocketsDo` themselves, I suppose we could stick a `withSocketsDo` around `withManager`. However, I'm concerned: does the old `withSocketsDo` nest safely?

**Comment by snoyberg** [comment]
> but at this point, shouldn't it be deprecated in favor of something like

But that's exactly the point of backwards compatibility: we *can't* deprecate it, use something else, and be compatible with preexisting versions in the wild. Many things might be nicer, but the fact is that we're stuck with a version of network out there that provides `withSocketsDo`, so we have to use it.

`withSocketsDo` can be nested safely; have a [look at the C functions](https://github.com/haskell/network/blob/v2.6.0.2/cbits/initWinSock.c).

**Comment by ndmitchell** [comment]
You really want to ditch `withSocketsDo` entirely, not replace it with another API which also is prone to easy mistakes. Simon Marlow's suggestion of a constructor attribute is a nice idea, but in the past some people have had absolute disasters with that attribute. The next GHCi uses the system linker, so things might improve there, but for the moment, the constructor is just too dangerous.

All versions of `withSocketsDo` nest safely, and you are also free to do socket operations after the function returns. These facts are now documented in the HEAD network library, and it says they apply to old versions too.

**Comment by DanBurton** [comment]
Thanks for explaining that, @ndmitchell. It makes a lot more sense to me now. We'll go ahead and call `withSocketsDo` in `newManager`; it's an easy change that should add some nice backwards-compatible convenience for all http-client use cases.

**Comment by snoyberg** [comment]
@ndmitchell can you confirm that PR #110 fixes this?

**Comment by ndmitchell** [comment]
Works for my example, seems very nice to me.

**Comment by snoyberg** [comment]
Cool, releasing to Hackage.
