### ISSUE TITLE
httpLbs does not throw exception for 401

### ISSUE THREAD

**Issue by MasterMastic** [snoyberg/http-client#237]
The [documentation](https://haskell-lang.org/library/http-client) states "By default, every request that generates a non-2XX response will generate a runtime exception.", however:

```
ghci> import qualified Network.HTTP.Client as Http
ghci> Http.httpLbs (Http.parseRequest_ "http://httpbin.org/status/401") =<< Http.newManager Http.defaultManagerSettings
Response {responseStatus = Status {statusCode = 401, statusMessage = "UNAUTHORIZED"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx"),("Date","Thu, 27 Oct 2016 10:38:22 GMT"),("Content-Length","0"),("Connection","keep-alive"),("Access-Control-Allow-Origin","*"),("WWW-Authenticate","Basic realm=\"Fake Realm\""),("Access-Control-Allow-Credentials","true")], responseBody = "", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
```

**Comment by snoyberg** [comment]
Good catch, this was a change in http-client 0.5. You interested in sending
a PR with an update to the docs?

**Comment by MasterMastic** [comment]
So this is intentional? how come? and is there any easy way to throw an `HttpException` for it?

I wouldn't mind updating the docs, but is 401 the only exception for an error-code that doesn't throw exceptions?

**Comment by mrkkrp** [comment]
Sorry for being dumb, but looking at the change log for version 0.5, I see:

* Remove instance Default Request
* Modify instance IsString Request to use parseRequest instead of parseUrlThrow
* Clean up the HttpException constructors
* Rename checkStatus to checkResponse and modify type
* Fix the ugly magic constant workaround for responseTimeout
* Remove getConnectionWrapper
* Add the HttpExceptionRequest wrapper so that all exceptions related to a request are thrown with that request's information

From all of these, only the last one seems to be somewhat relevant, but it says that a wrapper was added, even with the wrapper, it should still throw for non 2xx status codes something, but in the shown example it doesn't throw at all.

**Comment by snoyberg** [comment]
It's from the change to the IsString instance. The discussion around this
was: https://github.com/snoyberg/http-client/issues/193

**Comment by mrkkrp** [comment]
Ah well, I see. Would be helpful to add this change to the change log, at least retroactively, like “stopped throwing exceptions for non-2xx response status codes”.

So we need to update:

1. Changelog;
2. Docs of the package itself;
3. Perhaps the tutorial on https://haskell-lang.org as well.

I might have time to go through this this weekend, I'm working on an alternative to `wreq`, so I wanted to read source/docs of `http-client` closely anyway.

**Comment by mrkkrp** [comment]
OK, am I correct that whether we throw when actually performing request, with `httpLbs` for example, depends on how request was parsed from a string? So, `parseUrlThrow` will produce a request with the setting that makes it throw, and `parseRequest` perhaps produces a request that does not throw?

**Comment by mrkkrp** [comment]
@MasterMastic

> So this is intentional? how come? and is there any easy way to throw an HttpException for it?

So you need to parse your string with `parseUrlThrow` to get a request which will throw `HttpException` as you want:

```
λ> request <- L.parseUrlThrow "http://httpbin.org/status/401"
λ> L.httpLbs request =<< L.newManager L.defaultManagerSettings
*** Exception: HttpExceptionRequest Request {
  host                 = "httpbin.org"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/status/401"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (StatusCodeException (Response {responseStatus = Status {statusCode = 401, statusMessage = "UNAUTHORIZED"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx"),("Date","Thu, 27 Oct 2016 19:23:56 GMT"),("Content-Length","0"),("Connection","keep-alive"),("Access-Control-Allow-Origin","*"),("WWW-Authenticate","Basic realm=\"Fake Realm\""),("Access-Control-Allow-Credentials","true")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "")
```

“Throw” suffix in `parseUrlThrow` means that the resulting request is “throwable” (well, sadly, at the same time this function works in `MonadThrow` and it's easy to be fooled that “throw” suffix of because of `MonadThrow`).

It's not obvious that parsing influences throwability, I would argue that the first thought of 99% of users will be that request is well… request (collection of data/properties that describe a request), and whether you get an exception or not should depend on the way you run it, not how you parse it. In fact, the connection between parsing function and whether it will be thrown or not did not reveal itself until I looked straight at the source code. To help users this (not very obvious) idea should be introduced explicitly at the top of main module. It's better to mention explicitly all these considerations in docs.

@snoyberg Do you see any value in this reasoning and in updating docs accordingly?

**Comment by snoyberg** [comment]
I'll review the doc changes you've sent, explicit docs are always a good thing.

Any objection to closing this issue?

**Comment by MasterMastic** [comment]
Not from me; thanks a lot for your help, guys.
