### ISSUE TITLE
Memory leak hard to track when performing large amount of requests

### ISSUE THREAD

**Issue by carbolymer** [snoyberg/http-client#465]
When doing a large amount of HTTP requests (20k) in 500 concurrent threads, the application memory usage peaks. When trying to profile the application, the GHC profiller output shows no particular memory usage hotspot, and the heap profile explains only 50MB of 710MB used (7%!). 

That's an issue, because in our application we need to perform 20x more requests, resulting in ~17GB RAM usage in our case.

The minimal example together with my results: https://gitlab.com/carbolymer/network-http-client-memory-leak/

Any hints where I could proceed further with the investigation of this issue?

**Comment by snoyberg** [comment]
Two thoughts on this:

1. This is making an HTTPS request, not HTTP. Do you know for a fact that this only occurs with HTTPS? Because if so, it would be interesting to test against http-client-openssl as well.
2. I doubt the memory leak is coming from the concurrency code you've got there, but it looks like you could switch over to this function instead: https://www.stackage.org/haddock/nightly-2021-05-10/unliftio-0.2.15/UnliftIO-Async.html#v:pooledReplicateConcurrentlyN_

**Comment by carbolymer** [comment]
Thanks for fast reply. 
1. The issue persists also with HTTP.
2. That is the function I was looking for! What is very strange, after switching from my `mapConcurrently'` to `pooledReplicateConcurrentlyN_` memory usage dropped to 80MB in this minimal example. I didn't expect that behaviour from `QSem` implementation.

The bottom line, it looks like fault of `mapConcurrently'`. I'll keep the issue open for a couple of days in order to test it on our code and rule-out the http-client from this problem.

**Comment by carbolymer** [comment]
I confirm, that's not a http-client-related issue.
