### ISSUE TITLE
http-client: Request body is not relay on retry

### ISSUE THREAD

**Issue by kazu-yamamoto** [snoyberg/http-client#74]
`httpRaw` calls `httpRaw` via `responseOpen` again in the case where a _reused_ connection is closed (by its peer due to timeout or something). It seems to me that the first `httpRaw` consumes the request body, so the second `httpRaw` cannot send the necessary body.

This is a real problem in the reverse proxy feature of Mighty. Relaying POST fails sometime.

**Comment by matil019** [comment]
Nice to meet you. Recently I encountered the same behavior at the latest version of http-client. As of now, the request is sent twice, and its body spent at the first send.  
The workaround, which flushes the headers before the body, is not working, at least for now.

Here is the code that demonstrate the problem:

```foo.hs
#!/usr/bin/env stack
-- stack script --resolver lts-12.7
{-# LANGUAGE OverloadedStrings #-}
import qualified Conduit as C
import           Control.Concurrent (threadDelay)
import qualified Data.ByteString.Lazy.Char8 as L8
import           Network.HTTP.Client
import           Network.HTTP.Conduit (requestBodySourceIO)
import           Network.HTTP.Types.Status (statusCode)

main :: IO ()
main = do
    manager <- newManager defaultManagerSettings
    doRequest manager
    doRequest manager
  where
  doRequest manager = C.withSourceFile "foo.json" $ \f -> do
    -- this server sends FIN after 5 seconds
    initialRequest <- parseRequest "http://scooterlabs.com/echo"
    let request = initialRequest
         { method = "POST"
         , requestBody = requestBodySourceIO 11 f
         , requestHeaders =
            [ ("Content-Type", "application/json; charset=utf-8")
            ]
         }

    response <- httpLbs request manager
    putStrLn $ "The status code was: " ++ show (statusCode $ responseStatus response)
    L8.putStrLn $ responseBody response

    putStrLn $ "Sleeping for 6 seconds"
    threadDelay (6 * 1000 * 1000)
```

```foo.json
{ "a": 1 }
```

The program crashes after the second request with `WrongRequestBodyStreamSize 11 0`.

Building with `cabal` instead of `stack` doesn't change the behavior.

I think it's ok that `http-client` expects `GivesPopper` can be called multiple times. But then, isn't `requestBodySourceIO` incompatible with that requirement?
